// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PortalIUPA.Infrastructure.Persistence;

#nullable disable

namespace PortalIUPA.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260915123826_AddDisenoReportes")]
    partial class AddDisenoReportes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PortalIUPA.Domain.Entities.AccesoLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("accion");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("correo");

                    b.Property<string>("Dispositivo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dispositivo");

                    b.Property<Guid?>("EmpleadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("empleado_id");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip");

                    b.HasKey("Id");

                    b.HasIndex("FechaHora");

                    b.ToTable("accesos_log", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.Adjunto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<string>("EntidadTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entidad_tipo");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre_archivo");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("storage_key");

                    b.Property<long>("TamañoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano_bytes");

                    b.HasKey("Id");

                    b.HasIndex("EntidadTipo", "EntidadId");

                    b.ToTable("adjuntos", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.Anuncio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("Alcance")
                        .HasColumnType("integer")
                        .HasColumnName("alcance");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<Guid>("CreadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por");

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cuerpo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateOnly?>("FechaDesde")
                        .HasColumnType("date")
                        .HasColumnName("fecha_desde");

                    b.Property<DateOnly?>("FechaHasta")
                        .HasColumnType("date")
                        .HasColumnName("fecha_hasta");

                    b.Property<int>("Prioridad")
                        .HasColumnType("integer")
                        .HasColumnName("prioridad");

                    b.Property<int?>("Rol")
                        .HasColumnType("integer")
                        .HasColumnName("rol");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.ToTable("anuncios", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.AnuncioLeido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnuncioId")
                        .HasColumnType("uuid")
                        .HasColumnName("anuncio_id");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("empleado_id");

                    b.Property<DateTime>("FechaLectura")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_lectura");

                    b.HasKey("Id");

                    b.HasIndex("AnuncioId", "EmpleadoId")
                        .IsUnique();

                    b.ToTable("anuncios_leidos", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.Aprobacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AprobadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("aprobador_id");

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<Guid>("NivelAprobacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("nivel_aprobacion_id");

                    b.Property<int>("Resultado")
                        .HasColumnType("integer")
                        .HasColumnName("resultado");

                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitud_id");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudId");

                    b.ToTable("aprobaciones", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<Guid?>("AreaPadreId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_padre_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("AreaPadreId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("areas", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.CertificadoCurso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdjuntoId")
                        .HasColumnType("uuid")
                        .HasColumnName("adjunto_id");

                    b.Property<string>("ComentarioRevision")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comentario_revision");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("empleado_id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_carga");

                    b.Property<DateOnly>("FechaObtencion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_obtencion");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("institucion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId", "Estado");

                    b.ToTable("certificados_cv", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.CertificadoLaboral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArchivoAdjuntoId")
                        .HasColumnType("uuid")
                        .HasColumnName("archivo_adjunto_id");

                    b.Property<DateOnly>("Desde")
                        .HasColumnType("date")
                        .HasColumnName("desde");

                    b.Property<string>("Destino")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("destino");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("empleado_id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_solicitud");

                    b.Property<DateOnly>("Hasta")
                        .HasColumnType("date")
                        .HasColumnName("hasta");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("certificados_laborales", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.CvAntecedenteAcademico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdjuntoId")
                        .HasColumnType("uuid")
                        .HasColumnName("adjunto_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("empleado_id");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_carga");

                    b.Property<DateOnly>("FechaDesde")
                        .HasColumnType("date")
                        .HasColumnName("fecha_desde");

                    b.Property<DateOnly?>("FechaHasta")
                        .HasColumnType("date")
                        .HasColumnName("fecha_hasta");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("institucion");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId", "FechaDesde");

                    b.ToTable("cv_antecedentes_academicos", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.CvAntecedenteAdjunto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdjuntoId")
                        .HasColumnType("uuid")
                        .HasColumnName("adjunto_id");

                    b.Property<Guid>("AntecedenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("antecedente_id");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_carga");

                    b.HasKey("Id");

                    b.HasIndex("AdjuntoId");

                    b.HasIndex("AntecedenteId");

                    b.ToTable("cv_antecedente_adjuntos", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.CvAntecedenteItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("categoria");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("empleado_id");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_carga");

                    b.Property<DateOnly>("FechaDesde")
                        .HasColumnType("date")
                        .HasColumnName("fecha_desde");

                    b.Property<DateOnly?>("FechaHasta")
                        .HasColumnType("date")
                        .HasColumnName("fecha_hasta");

                    b.Property<string>("Institucion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("institucion");

                    b.Property<int>("Seccion")
                        .HasColumnType("integer")
                        .HasColumnName("seccion");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId", "Seccion");

                    b.ToTable("cv_antecedente_items", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.CvAntecedenteItemAdjunto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdjuntoId")
                        .HasColumnType("uuid")
                        .HasColumnName("adjunto_id");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_carga");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.HasKey("Id");

                    b.HasIndex("AdjuntoId");

                    b.HasIndex("ItemId");

                    b.ToTable("cv_item_adjuntos", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.CvExperiencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("empleado_id");

                    b.Property<DateOnly>("FechaDesde")
                        .HasColumnType("date")
                        .HasColumnName("fecha_desde");

                    b.Property<DateOnly?>("FechaHasta")
                        .HasColumnType("date")
                        .HasColumnName("fecha_hasta");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("institucion");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("puesto");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId", "FechaDesde");

                    b.ToTable("cv_experiencias", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.CvExperienciaAdjunto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdjuntoId")
                        .HasColumnType("uuid")
                        .HasColumnName("adjunto_id");

                    b.Property<Guid>("ExperienciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("experiencia_id");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_carga");

                    b.HasKey("Id");

                    b.HasIndex("AdjuntoId");

                    b.HasIndex("ExperienciaId");

                    b.ToTable("cv_experiencia_adjuntos", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.DescargaRecibo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("empleado_id");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip");

                    b.Property<int>("Origen")
                        .HasColumnType("integer")
                        .HasColumnName("origen");

                    b.Property<Guid>("PeriodoId")
                        .HasColumnType("uuid")
                        .HasColumnName("periodo_id");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId", "PeriodoId");

                    b.ToTable("descargas_recibo", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.Edificio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<double>("Latitud")
                        .HasColumnType("double precision")
                        .HasColumnName("latitud");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision")
                        .HasColumnName("longitud");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<int>("RadioMetros")
                        .HasColumnType("integer")
                        .HasColumnName("radio_metros");

                    b.HasKey("Id");

                    b.ToTable("edificios", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.Empleado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("apellido");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("correo");

                    b.Property<string>("Cuil")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cuil");

                    b.Property<string>("CvObservaciones")
                        .HasColumnType("text")
                        .HasColumnName("cv_observaciones");

                    b.Property<string>("CvTelefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cv_telefono");

                    b.Property<string>("Dni")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dni");

                    b.Property<int>("Legajo")
                        .HasColumnType("integer")
                        .HasColumnName("legajo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<int[]>("Roles")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("roles");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("Legajo")
                        .IsUnique();

                    b.ToTable("empleados", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.MarcaReloj", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EdificioId")
                        .HasColumnType("uuid")
                        .HasColumnName("edificio_id");

                    b.Property<string>("EdificioNombre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("edificio_nombre");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("empleado_id");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double precision")
                        .HasColumnName("latitud");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double precision")
                        .HasColumnName("longitud");

                    b.Property<string>("Origen")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("origen");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_marca");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId", "FechaHora")
                        .IsUnique();

                    b.ToTable("marcas_reloj", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cuerpo");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("empleado_id");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean")
                        .HasColumnName("leida");

                    b.Property<string>("Link")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("link");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId", "Leida");

                    b.ToTable("notificaciones", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.Periodo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("NroLiq")
                        .HasColumnType("integer")
                        .HasColumnName("nro_liq");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("periodos", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.RelacionACargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutorizaMarcas")
                        .HasColumnType("boolean")
                        .HasColumnName("autoriza_marcas");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("empleado_id");

                    b.Property<DateOnly>("FechaDesde")
                        .HasColumnType("date")
                        .HasColumnName("fecha_desde");

                    b.Property<DateOnly?>("FechaHasta")
                        .HasColumnType("date")
                        .HasColumnName("fecha_hasta");

                    b.Property<Guid>("ResponsableId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsable_id");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ResponsableId");

                    b.ToTable("relaciones_a_cargo", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.RelojZk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("CommKey")
                        .HasColumnType("integer")
                        .HasColumnName("comm_key");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip");

                    b.Property<string>("Modo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("modo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<int>("Puerto")
                        .HasColumnType("integer")
                        .HasColumnName("puerto");

                    b.Property<int>("UltimaCantidad")
                        .HasColumnType("integer")
                        .HasColumnName("ultima_cantidad");

                    b.Property<DateTime?>("UltimaDescarga")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ultima_descarga");

                    b.HasKey("Id");

                    b.ToTable("relojes_zk", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.RelojZkDescarga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Duplicadas")
                        .HasColumnType("integer")
                        .HasColumnName("duplicadas");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("LegajosDesconocidos")
                        .HasColumnType("integer")
                        .HasColumnName("legajos_desconocidos");

                    b.Property<int>("Leidas")
                        .HasColumnType("integer")
                        .HasColumnName("leidas");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("mensaje");

                    b.Property<int>("Nuevas")
                        .HasColumnType("integer")
                        .HasColumnName("nuevas");

                    b.Property<Guid>("RelojZkId")
                        .HasColumnType("uuid")
                        .HasColumnName("reloj_zk_id");

                    b.Property<string>("UsuarioCorreo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("usuario_correo");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.ToTable("relojes_zk_descargas", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.ReporteDefinicion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Conexion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("PortalIUPA")
                        .HasColumnName("conexion");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("CreadoPorEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("creado_por_email");

                    b.Property<string>("DefinicionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definicion");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descripcion");

                    b.Property<string>("DisenoJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("diseno");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("QuerySql")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query_sql");

                    b.HasKey("Id");

                    b.ToTable("reportes", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.ReportePermiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<Guid>("ReporteId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporte_id");

                    b.Property<string>("Rol")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.HasIndex("ReporteId");

                    b.ToTable("reportes_permisos", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.SolicitudLicencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdjuntoId")
                        .HasColumnType("uuid")
                        .HasColumnName("adjunto_id");

                    b.Property<string>("Asunto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("asunto");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("empleado_id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_solicitud");

                    b.Property<string>("Motivo")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("motivo");

                    b.Property<Guid>("TipoLicenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_licencia_id");

                    b.HasKey("Id");

                    b.HasIndex("TipoLicenciaId");

                    b.HasIndex("EmpleadoId", "Estado");

                    b.ToTable("solicitudes_licencia", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.TipoLicencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("LimiteAnual")
                        .HasColumnType("integer")
                        .HasColumnName("limite_anual");

                    b.Property<int?>("LimiteMensual")
                        .HasColumnType("integer")
                        .HasColumnName("limite_mensual");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<bool>("RequiereAdjunto")
                        .HasColumnType("boolean")
                        .HasColumnName("requiere_adjunto");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("tipos_licencia", (string)null);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.Area", b =>
                {
                    b.HasOne("PortalIUPA.Domain.Entities.Area", null)
                        .WithMany()
                        .HasForeignKey("AreaPadreId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.Empleado", b =>
                {
                    b.HasOne("PortalIUPA.Domain.Entities.Area", null)
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.ReportePermiso", b =>
                {
                    b.HasOne("PortalIUPA.Domain.Entities.ReporteDefinicion", null)
                        .WithMany("Permisos")
                        .HasForeignKey("ReporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.TipoLicencia", b =>
                {
                    b.OwnsMany("PortalIUPA.Domain.Entities.NivelAprobacion", "Niveles", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int>("Orden")
                                .HasColumnType("integer")
                                .HasColumnName("orden");

                            b1.Property<int>("RolRequerido")
                                .HasColumnType("integer")
                                .HasColumnName("rol_requerido");

                            b1.Property<Guid>("TipoLicenciaId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("TipoLicenciaId");

                            b1.ToTable("niveles_aprobacion", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TipoLicenciaId");
                        });

                    b.Navigation("Niveles");
                });

            modelBuilder.Entity("PortalIUPA.Domain.Entities.ReporteDefinicion", b =>
                {
                    b.Navigation("Permisos");
                });
#pragma warning restore 612, 618
        }
    }
}
